baseURL = 'https://antonle.me/'
languageCode = 'en-gb'
title = 'Anton Le'
theme = 'archie'

# code highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname" # todo: temp remove disqus comments and figure out whether they are needed at all or not

paginate = 3 # articles per page

[params]
mode = "auto" # color-mode → light,dark,toggle or auto
useCDN = false
subtitle = "Building in progress"
mathjax = true
katex = true

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/leanton"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/leanton/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
